### ISSUE TITLE
Feature Requests: Add Tx Signing 

### ISSUE THREAD

**Issue by jcrubino** [BitcoinMafia/SpareCoinsExt#10]
Add capability to sign standard and non standard p2sh transactions

**Comment by sidazhang** [comment]
@jcrubino sorry, didn't see this earlier. 

We are about to switch dependency to cryptocoinjs (whch is basically bitcoinjs lib but actively maintained)
https://github.com/cryptocoinjs/btc-script

There is some support for p2sh. I would like to add support for this here
