### ISSUE TITLE
Private & Public Keys

### ISSUE THREAD

**Issue by jcrubino** [BitcoinMafia/SpareCoinsExt#14]
Is there a function to access private and public key pairs once the address is generated?

**Comment by sidazhang** [comment]
@jcrubino,

Hey may I ask what your use case was? There is a function or there is also an export button on the UI

**Comment by jcrubino** [comment]
It turns out I was just not looking hard enough in the settings section

```
var entropy = random();
var hash_str = Crypto.SHA256(entropy);
var hash = Crypto.util.hexToBytes(hash_str);
var pubkey = new Bitcoin.ECKey(hash);
var addr = pubkey.getBitcoinAddress().toString();
var privkey = new Bitcoin.Address(hash);
```

Is the above the correct routine for address and key generation?

**Comment by sidazhang** [comment]
That looks about right. 

Although I would recommend using the https://github.com/cryptocoinjs/btc-address library. 

BitcoinJS was not maintained for a very long time and (recently seemed to have been maintained again). Cryptocoinjs is a fork of bitcoinjs which we plan to migrate sparecoins over

**Comment by jcrubino** [comment]
@sidazhang 
I have looked at cryptojs and am I am also evaluating the [bitpay bitcore](https://github.com/bitpay/bitcore) lib as a way to make the wallet and tranasction functions one object to work with....

**Comment by sidazhang** [comment]
Let me know what you think of bitcore! I haven't looked into that lib
