### ISSUE TITLE
Package is invalid. Details: 'Could not load background script 'lib/sparecoins.js'.'.

### ISSUE THREAD

**Issue by deizel** [BitcoinMafia/SpareCoinsExt#3]
Cannot install from Chrome Web Store - might need tested on Linux.

![error](https://f.cloud.github.com/assets/24155/1726969/7b71e328-6297-11e3-8e60-1bae03f2f645.png)

Google Chrome OS

Version 31.0.1650.62
Platform 4731.81.0 (Official Build) stable-channel daisy
Firmware Google_Snow.2695.117.0

Currently on stable channel.

WebKit: 537.36 (@162142)

V8: 3.21.18.9

Build Date: Thursday, November 28, 2013

---

Also reported on [Reddit thread](http://www.reddit.com/r/Bitcoin/comments/1sn5ww/introducing_sparecoins_we_got_tired_of_clunky/) under following versions:
- Ubuntu 12.04 Chromium 64bit
- Chromium 30.0.1599.114 (Developer Build 30.0.1599.114-0ubuntu0.13.10.2) Ubuntu 13.10

**Comment by deizel** [comment]
Solution found in [Reddit comment](http://www.reddit.com/r/Bitcoin/comments/1sn5ww/introducing_sparecoins_we_got_tired_of_clunky/cdzcbob) - after doing as follows, extension can be installed:

```
mv lib/spareCoins.js lib/sparecoins.js
```

**Comment by scottlingran** [comment]
Ahhh, git is case-insensitive with filenames

http://nova-fusion.com/2011/08/31/changing-filename-case-in-git/

Should be fixed now.

**Comment by scottlingran** [comment]
@deizel thanks for helping us debug. Fix has now been deployed on the Chrome Store. Should read version 1.0.9

**Comment by deizel** [comment]
Worked first time :thumbsup:
