### ISSUE TITLE
CRITICAL BUG

### ISSUE THREAD

**Issue by cilphex** [BitcoinMafia/SpareCoinsExt#5]
Uncaught Error: [object Object]

chrome-extension://nhkolgoaflkjhfkamdhiahingnendokj/js/app.js

36

**Comment by cilphex** [comment]
I got this once, and now every subsequent time I open the extension, it shows the UI for a split second, then shows this error again.

**Comment by scottlingran** [comment]
@sidazhang Looks like `BitcoinNodeAPI.multiAddr` is throwing an error on callback. Makes sense given cliphex is seeing the UI for a split second.

`BitcoinNodeAPI.multiAddr` throws an error only when the Bitcoin addresses are malformed.

@cilphex, is anything else logging in the console?

**Comment by sidazhang** [comment]
@locksley uncaught error [object Object], you sure its because the address is malformed?

If this is an issue that happens every now and then it could be an issue with blockchain API. They occasionally return an error. 

I haven't personally seen this yet though.

**Comment by scottlingran** [comment]
@cilphex, pretty sure this was a network error issue, was your computer offline or patchy wifi? Just deployed the fix on Chrome Store, v1.0.11

Let us know if it's still a problem.

**Comment by cilphex** [comment]
It gave me a new address and the bitcoin I sent to the first one is
apparently just lost.

**Comment by scottlingran** [comment]
What do you mean lost? Are you sure you can't see the other address in "History" or "See All Addresses?"

Addresses are stored in Chrome Storage and should never be cleared unless you do `chrome.storage.local.clear()` in  console.

**Comment by cilphex** [comment]
I only see one transaction in History, whcih is a new transaction from
today.  The address I sent to doesn't appear under All Addresses.  Maybe it
was another computer, not sure.  But I thought this synced across my
Chromes, maybe it doesn't?

**Comment by sidazhang** [comment]
@cilphex hey, its not currently synced across your chromes. All keys are stored locally in each browser. So unfortunately, at this stage you would have to move funds between browsers.

This is a decision we made after a few people expressed concerns about their encrypted keys being synced.

I personally think it would be far more convenient to have them synced. Out of curiosity, how comfortable are you with syncing your encrypted keys? Do you think it might be a good feature to have?

**Comment by sidazhang** [comment]
@cilphex do you still have the same issues? If not, I will close this ticket
